"""OmniVoxtral generation script — produce audio from the model.

Takes a trained checkpoint (or untrained model) and generates audio
via autoregressive temporal + depth decoding, then Mimi decode to wav.

Usage:
    # Generate from a checkpoint:
    CUDA_VISIBLE_DEVICES=0 uv run scripts/generate.py --ckpt_path checkpoints/step_2000.pt

    # Generate from scratch (random init, for pipeline validation):
    CUDA_VISIBLE_DEVICES=0 uv run scripts/generate.py --max_windows 20

    # Generate with a real data prompt (first N tokens from a .npy file):
    CUDA_VISIBLE_DEVICES=0 uv run scripts/generate.py --prompt_file data/tokens_fleurs/hi/hi/hi_000000_*.npy --prompt_tokens 100
"""

import argparse
import time

import dotenv
import numpy as np
import torch
import torchaudio

from voxtral.model.omnivoxtral import OmniVoxtral, OmniVoxtralConfig
from voxtral.tokenizer.model import VoxtralTokenizer, VoxtralTokenizerConfig
from voxtral.trainer.config import VoxtralTrainConfig

dotenv.load_dotenv()


def build_model(config: VoxtralTrainConfig, device: torch.device) -> OmniVoxtral:
    """Build OmniVoxtral model, optionally load checkpoint."""
    tok_cfg = config.voxtral_tokenizer_config
    omni_config = OmniVoxtralConfig(
        temporal_pretrained_path=config.mistral_pretrained_path,
        temporal_kwargs=config.mistral_kwargs,
        new_vocab_size=config.new_vocab_size,
        prune_layers=config.prune_layers,
        lora_rank=config.lora_rank,
        text_vocab_size=tok_cfg.text_vocab_size,
        num_codebooks=tok_cfg.mimi_num_quantizers,
        codebook_size=(config.new_vocab_size - tok_cfg.text_vocab_size) // tok_cfg.mimi_num_quantizers,
        text_hz=tok_cfg.text_hz,
        dual_stream=config.dual_stream,
        language_adapters=config.language_adapters,
        depth_num_layers=config.depth_num_layers,
        depth_dim=config.depth_dim,
        depth_num_heads=config.depth_num_heads,
        depth_dropout=0.0,  # No dropout at inference
    )

    model = OmniVoxtral(omni_config)

    # Apply LoRA if configured (must happen before loading compact checkpoint)
    if config.lora_rank is not None:
        import peft
        attn_names = {"q_proj", "k_proj", "v_proj", "o_proj"}
        lora_target_modules = [
            name
            for name, module in model.temporal.named_modules()
            if isinstance(module, torch.nn.Linear)
            and any(a in name for a in attn_names)
        ]
        lora_cfg = peft.LoraConfig(
            r=config.lora_rank,
            lora_alpha=config.lora_rank * 2,
            target_modules=lora_target_modules,
            bias="none",
            task_type=peft.TaskType.CAUSAL_LM,
            modules_to_save=["model.embed_tokens"],
        )
        model.temporal = peft.get_peft_model(model.temporal, lora_cfg)

    model = model.to(device, torch.bfloat16)
    model.eval()
    return model


def load_checkpoint(model: OmniVoxtral, ckpt_path: str, device: torch.device) -> None:
    """Load model weights from checkpoint. Handles both full and compact (LoRA) checkpoints."""
    checkpoint = torch.load(ckpt_path, map_location=device, weights_only=False)
    if checkpoint.get("compact"):
        # Compact LoRA checkpoint: adapter weights + depth only
        import peft
        peft.set_peft_model_state_dict(model.temporal, checkpoint["temporal_lora"])
        model.depth.load_state_dict(checkpoint["depth"])
        print(f"Loaded compact LoRA checkpoint from {ckpt_path} (step {checkpoint.get('step', '?')})")
    elif "model" in checkpoint:
        model.load_state_dict(checkpoint["model"], strict=False)
        print(f"Loaded checkpoint from {ckpt_path} (step {checkpoint.get('step', '?')})")
    else:
        model.load_state_dict(checkpoint, strict=False)
        print(f"Loaded raw state dict from {ckpt_path}")


@torch.no_grad()
def generate_tokens(
    model: OmniVoxtral,
    prompt: torch.Tensor | None,
    max_windows: int,
    temperature: float,
    top_k: int | None,
    device: torch.device,
    repetition_penalty: float = 1.0,
) -> torch.Tensor:
    """Autoregressive generation of interleaved token sequence.

    Each window = 1 text token + audio_per_window audio tokens = stride tokens.
    Audio tokens are generated by calling the depth transformer for each Mimi frame
    (8 codebooks per frame, 2-3 frames per window depending on stride).

    Training stride = 21: 1 text + 20 audio (= 2.5 Mimi frames at 8 codebooks).
    We generate 3 complete depth frames (24 tokens) and keep only the first 20.
    """
    num_q = model.config.num_codebooks  # 8
    text_vocab = model.config.text_vocab_size
    codebook_size = model.config.codebook_size
    stride = model.config.stride  # 21
    audio_per_window = model.config.text_to_audio_factor  # 20

    # Initialize context
    if prompt is not None:
        context = prompt.to(device).unsqueeze(0) if prompt.dim() == 1 else prompt.to(device)
    else:
        # Start with a random text token
        context = torch.randint(0, text_vocab, (1, 1), device=device)

    print(f"Generating {max_windows} windows ({max_windows * stride} tokens, "
          f"~{max_windows / 5:.1f}s audio at stride={stride})...")
    t0 = time.time()

    for win_idx in range(max_windows):
        # 1. Generate text token from temporal transformer
        temporal_hidden, temporal_logits = model._temporal_forward(context)
        text_logits = temporal_logits[:, -1, :text_vocab]
        # Apply repetition penalty to tokens seen in recent context
        if repetition_penalty != 1.0:
            recent = context[0, -stride * 10:] if context.shape[1] > stride * 10 else context[0]
            seen = recent.unique()
            text_seen = seen[seen < text_vocab]
            if len(text_seen) > 0:
                text_logits[:, text_seen] /= repetition_penalty
        text_token = model._sample_token(text_logits, temperature, top_k)
        context = torch.cat([context, text_token], dim=1)

        # 2. Generate audio_per_window audio tokens via depth transformer
        #    Each depth call produces num_q (8) codebook tokens for one Mimi frame.
        #    We need audio_per_window (20) tokens = ceil(20/8) = 3 depth calls,
        #    keeping only the first 20 tokens.
        audio_generated = 0
        while audio_generated < audio_per_window:
            # Get fresh hidden state after appending previous tokens
            temporal_hidden, _ = model._temporal_forward(context)
            h_last = temporal_hidden[:, -1, :]

            # Depth generates one complete frame (8 codebook tokens)
            frame_tokens = model.depth.generate(
                h_last, temperature=temperature, top_k=top_k
            )  # (1, num_q)

            # Only take as many tokens as needed to fill the window
            tokens_needed = min(num_q, audio_per_window - audio_generated)
            for q in range(tokens_needed):
                global_tok = text_vocab + q * codebook_size + frame_tokens[:, q]
                context = torch.cat([context, global_tok.unsqueeze(1)], dim=1)

            audio_generated += tokens_needed

        if (win_idx + 1) % 10 == 0:
            elapsed = time.time() - t0
            wps = (win_idx + 1) / elapsed
            print(f"  Window {win_idx + 1}/{max_windows} ({wps:.1f} win/sec)")

    elapsed = time.time() - t0
    total_tokens = context.shape[1]
    print(f"Generated {total_tokens} tokens in {elapsed:.1f}s ({total_tokens / elapsed:.0f} tok/s)")

    return context.squeeze(0)


def tokens_to_audio(
    tokens: torch.Tensor,
    tokenizer: VoxtralTokenizer,
) -> torch.Tensor:
    """Decode interleaved tokens to audio waveform via Mimi."""
    if tokens.dim() == 1:
        tokens = tokens.unsqueeze(0)
    # Truncate to valid length: must be a multiple of stride AND total audio
    # tokens must be divisible by num_quantizers. With stride=21 (1 text + 20 audio)
    # and num_q=8: 20*N must be divisible by 8, so N must be even.
    stride = tokenizer.text_to_audio_token_factor + 1
    num_q = tokenizer.config.mimi_num_quantizers
    audio_per_window = tokenizer.text_to_audio_token_factor
    # Find the window grouping needed: LCM(audio_per_window, num_q) / audio_per_window
    from math import gcd
    window_group = num_q // gcd(audio_per_window, num_q)  # = 2 for 20/8
    valid_windows = (tokens.size(1) // stride // window_group) * window_group
    valid_len = valid_windows * stride
    tokens = tokens[:, :valid_len]
    audio = tokenizer.decode(tokens)
    return audio.squeeze(0)


def main():
    parser = argparse.ArgumentParser(description="Generate audio from OmniVoxtral")
    parser.add_argument("--ckpt_path", type=str, default=None)
    parser.add_argument("--prompt_file", type=str, default=None)
    parser.add_argument("--prompt_tokens", type=int, default=100)
    parser.add_argument("--max_windows", type=int, default=20, help="Windows to generate (~4s at 5Hz, stride=21)")
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top_k", type=int, default=250, help="Top-k filtering for sampling (250=good default, None=no filter)")
    parser.add_argument("--output", type=str, default="generated.wav")
    parser.add_argument("--repetition_penalty", type=float, default=1.2, help="Repetition penalty for text tokens (1.0=off, 1.2=default)")
    parser.add_argument("--device", type=str, default="cuda:0")
    args = parser.parse_args()

    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    config = VoxtralTrainConfig()

    print("=== OmniVoxtral Generation ===")
    print(f"  Model: {config.mistral_pretrained_path}")
    print(f"  Depth: {config.depth_num_layers}L")
    print(f"  Checkpoint: {args.ckpt_path or 'random init'}")
    print(f"  Windows: {args.max_windows} (~{args.max_windows / 5:.1f}s audio at 5Hz)")
    print(f"  Temperature: {args.temperature}")
    print()

    # Build model
    print("Loading model...")
    model = build_model(config, device)
    if args.ckpt_path:
        load_checkpoint(model, args.ckpt_path, device)

    # EMBNORM-1: Rescale speech embeddings to match text embedding norms.
    # Speech embeddings are ~4x larger than text, causing attention dominance
    # and repetitive generation. Rescale each to match text mean norm.
    embed_w = model.temporal.get_input_embeddings().weight
    text_vocab = config.voxtral_tokenizer_config.text_vocab_size
    with torch.no_grad():
        text_mean_norm = embed_w[:text_vocab].norm(dim=1).mean()
        speech_norms = embed_w[text_vocab:].norm(dim=1, keepdim=True).clamp(min=1e-8)
        embed_w[text_vocab:] *= text_mean_norm / speech_norms
        print(f"  Embedding rescaling: speech norms → {text_mean_norm:.4f} (was ~{(speech_norms.mean() * text_mean_norm / text_mean_norm).item():.4f})")

    # Load prompt if provided
    prompt = None
    if args.prompt_file:
        prompt_data = np.load(args.prompt_file)
        prompt = torch.from_numpy(prompt_data).squeeze()
        if args.prompt_tokens and args.prompt_tokens < len(prompt):
            prompt = prompt[:args.prompt_tokens]
        print(f"Prompt: {len(prompt)} tokens from {args.prompt_file}")

    # Generate tokens
    tokens = generate_tokens(
        model=model,
        prompt=prompt,
        max_windows=args.max_windows,
        temperature=args.temperature,
        top_k=args.top_k,
        device=device,
        repetition_penalty=args.repetition_penalty,
    )

    print(f"\nGenerated token sequence: {tokens.shape}")
    print(f"  Range: [{tokens.min().item()}, {tokens.max().item()}]")

    # Decode to audio
    print("Loading Mimi tokenizer for audio decoding...")
    tok_config = config.voxtral_tokenizer_config
    tokenizer = VoxtralTokenizer(tok_config)
    tokenizer = tokenizer.to(device=device, dtype=torch.float16)

    print("Decoding tokens to audio...")
    audio = tokens_to_audio(tokens, tokenizer)
    print(f"  Audio shape: {audio.shape}")
    print(f"  Duration: {audio.shape[-1] / 24000:.2f}s at 24kHz")

    # Save wav
    audio_cpu = audio.cpu().float()
    if audio_cpu.dim() == 1:
        audio_cpu = audio_cpu.unsqueeze(0)
    torchaudio.save(args.output, audio_cpu, 24000)
    print(f"\nSaved: {args.output}")
    print("=== Done ===")


if __name__ == "__main__":
    main()
