"""OmniVoxtral generation script — produce audio from the model.

Takes a trained checkpoint (or untrained model) and generates audio
via autoregressive temporal + depth decoding, then Mimi decode to wav.

Usage:
    # CLI:
    CUDA_VISIBLE_DEVICES=0 uv run scripts/generate.py --ckpt_path checkpoints/step_2000.pt
    CUDA_VISIBLE_DEVICES=0 uv run scripts/generate.py --max_windows 20
    CUDA_VISIBLE_DEVICES=0 uv run scripts/generate.py --prompt_file data/tokens_fleurs/hi/hi/hi_000000_*.npy --prompt_tokens 100

    # Module (used by tests/eval_wer.py):
    from scripts.generate import load_inference_pipeline, generate_audio
    pipeline = load_inference_pipeline("ckpt.pt", device="cuda:0")
    waveform = generate_audio(pipeline, prompt_audio=fleurs_array, language="hin",
                              prompt_sample_rate=16000, max_windows=150)
"""

from __future__ import annotations

import argparse
import time
from dataclasses import dataclass
from typing import Optional

import dotenv
import numpy as np
import torch
import torchaudio

from voxtral.model.omnivoxtral import OmniVoxtral, OmniVoxtralConfig
from voxtral.tokenizer.model import VoxtralTokenizer, VoxtralTokenizerConfig
from voxtral.trainer.config import VoxtralTrainConfig

dotenv.load_dotenv()


@dataclass
class InferencePipeline:
    """Bundle of objects needed for inference. Instantiate via
    `load_inference_pipeline()`. Reused across multiple generations of the same
    checkpoint to amortize the model+Mimi load cost."""
    model: OmniVoxtral
    tokenizer: VoxtralTokenizer
    config: VoxtralTrainConfig
    device: torch.device


def build_model(config: VoxtralTrainConfig, device: torch.device) -> OmniVoxtral:
    """Build OmniVoxtral model, optionally load checkpoint."""
    tok_cfg = config.voxtral_tokenizer_config
    omni_config = OmniVoxtralConfig(
        temporal_pretrained_path=config.mistral_pretrained_path,
        temporal_kwargs=config.mistral_kwargs,
        new_vocab_size=config.new_vocab_size,
        prune_layers=config.prune_layers,
        lora_rank=config.lora_rank,
        text_vocab_size=tok_cfg.text_vocab_size,
        num_codebooks=tok_cfg.mimi_num_quantizers,
        codebook_size=(config.new_vocab_size - tok_cfg.text_vocab_size) // tok_cfg.mimi_num_quantizers,
        text_hz=tok_cfg.text_hz,
        dual_stream=config.dual_stream,
        language_adapters=config.language_adapters,
        depth_num_layers=config.depth_num_layers,
        depth_dim=config.depth_dim,
        depth_num_heads=config.depth_num_heads,
        depth_dropout=0.0,  # No dropout at inference
    )

    model = OmniVoxtral(omni_config)

    # Apply LoRA if configured (must happen before loading compact checkpoint)
    if config.lora_rank is not None:
        import peft
        attn_names = {"q_proj", "k_proj", "v_proj", "o_proj"}
        lora_target_modules = [
            name
            for name, module in model.temporal.named_modules()
            if isinstance(module, torch.nn.Linear)
            and any(a in name for a in attn_names)
        ]
        lora_cfg = peft.LoraConfig(
            r=config.lora_rank,
            lora_alpha=config.lora_rank * 2,
            target_modules=lora_target_modules,
            bias="none",
            task_type=peft.TaskType.CAUSAL_LM,
            modules_to_save=["model.embed_tokens"],
        )
        model.temporal = peft.get_peft_model(model.temporal, lora_cfg)

    model = model.to(device, torch.bfloat16)
    model.eval()
    return model


def load_checkpoint(model: OmniVoxtral, ckpt_path: str, device: torch.device) -> None:
    """Load model weights from checkpoint. Handles both full and compact (LoRA) checkpoints."""
    checkpoint = torch.load(ckpt_path, map_location=device, weights_only=False)
    if checkpoint.get("compact"):
        # Compact LoRA checkpoint: adapter weights + depth only
        import peft
        peft.set_peft_model_state_dict(model.temporal, checkpoint["temporal_lora"])
        model.depth.load_state_dict(checkpoint["depth"])
        print(f"Loaded compact LoRA checkpoint from {ckpt_path} (step {checkpoint.get('step', '?')})")
    elif "model" in checkpoint:
        model.load_state_dict(checkpoint["model"], strict=False)
        print(f"Loaded checkpoint from {ckpt_path} (step {checkpoint.get('step', '?')})")
    else:
        model.load_state_dict(checkpoint, strict=False)
        print(f"Loaded raw state dict from {ckpt_path}")


@torch.no_grad()
def generate_tokens(
    model: OmniVoxtral,
    prompt: torch.Tensor | None,
    max_windows: int,
    temperature: float,
    top_k: int | None,
    device: torch.device,
    repetition_penalty: float = 1.0,
) -> torch.Tensor:
    """Autoregressive generation of interleaved token sequence.

    Each window = 1 text token + audio_per_window audio tokens = stride tokens.
    Audio tokens are generated by calling the depth transformer for each Mimi frame
    (8 codebooks per frame, 2-3 frames per window depending on stride).

    Training stride = 21: 1 text + 20 audio (= 2.5 Mimi frames at 8 codebooks).
    We generate 3 complete depth frames (24 tokens) and keep only the first 20.
    """
    num_q = model.config.num_codebooks  # 8
    text_vocab = model.config.text_vocab_size
    codebook_size = model.config.codebook_size
    stride = model.config.stride  # 21
    audio_per_window = model.config.text_to_audio_factor  # 20

    # Initialize context
    if prompt is not None:
        context = prompt.to(device).unsqueeze(0) if prompt.dim() == 1 else prompt.to(device)
    else:
        # Start with a random text token
        context = torch.randint(0, text_vocab, (1, 1), device=device)

    print(f"Generating {max_windows} windows ({max_windows * stride} tokens, "
          f"~{max_windows / 5:.1f}s audio at stride={stride})...")
    t0 = time.time()

    for win_idx in range(max_windows):
        # 1. Generate text token from temporal transformer
        temporal_hidden, temporal_logits = model._temporal_forward(context)
        text_logits = temporal_logits[:, -1, :text_vocab]
        # Apply repetition penalty to tokens seen in recent context
        if repetition_penalty != 1.0:
            recent = context[0, -stride * 10:] if context.shape[1] > stride * 10 else context[0]
            seen = recent.unique()
            text_seen = seen[seen < text_vocab]
            if len(text_seen) > 0:
                text_logits[:, text_seen] /= repetition_penalty
        text_token = model._sample_token(text_logits, temperature, top_k)
        context = torch.cat([context, text_token], dim=1)

        # 2. Generate audio_per_window audio tokens via depth transformer
        #    Each depth call produces num_q (8) codebook tokens for one Mimi frame.
        #    We need audio_per_window (20) tokens = ceil(20/8) = 3 depth calls,
        #    keeping only the first 20 tokens.
        audio_generated = 0
        while audio_generated < audio_per_window:
            # Get fresh hidden state after appending previous tokens
            temporal_hidden, _ = model._temporal_forward(context)
            h_last = temporal_hidden[:, -1, :]

            # Depth generates one complete frame (8 codebook tokens)
            frame_tokens = model.depth.generate(
                h_last, temperature=temperature, top_k=top_k
            )  # (1, num_q)

            # Only take as many tokens as needed to fill the window
            tokens_needed = min(num_q, audio_per_window - audio_generated)
            for q in range(tokens_needed):
                global_tok = text_vocab + q * codebook_size + frame_tokens[:, q]
                context = torch.cat([context, global_tok.unsqueeze(1)], dim=1)

            audio_generated += tokens_needed

        if (win_idx + 1) % 10 == 0:
            elapsed = time.time() - t0
            wps = (win_idx + 1) / elapsed
            print(f"  Window {win_idx + 1}/{max_windows} ({wps:.1f} win/sec)")

    elapsed = time.time() - t0
    total_tokens = context.shape[1]
    print(f"Generated {total_tokens} tokens in {elapsed:.1f}s ({total_tokens / elapsed:.0f} tok/s)")

    return context.squeeze(0)


def tokens_to_audio(
    tokens: torch.Tensor,
    tokenizer: VoxtralTokenizer,
) -> torch.Tensor:
    """Decode interleaved tokens to audio waveform via Mimi."""
    if tokens.dim() == 1:
        tokens = tokens.unsqueeze(0)
    # Truncate to valid length: must be a multiple of stride AND total audio
    # tokens must be divisible by num_quantizers. With stride=21 (1 text + 20 audio)
    # and num_q=8: 20*N must be divisible by 8, so N must be even.
    stride = tokenizer.text_to_audio_token_factor + 1
    num_q = tokenizer.config.mimi_num_quantizers
    audio_per_window = tokenizer.text_to_audio_token_factor
    # Find the window grouping needed: LCM(audio_per_window, num_q) / audio_per_window
    from math import gcd
    window_group = num_q // gcd(audio_per_window, num_q)  # = 2 for 20/8
    valid_windows = (tokens.size(1) // stride // window_group) * window_group
    valid_len = valid_windows * stride
    tokens = tokens[:, :valid_len]
    audio = tokenizer.decode(tokens)
    return audio.squeeze(0)


def load_inference_pipeline(
    ckpt_path: Optional[str],
    config: Optional[VoxtralTrainConfig] = None,
    device: str | torch.device = "cuda:0",
) -> InferencePipeline:
    """Load model + Mimi tokenizer ready for inference.

    Designed to be called once per checkpoint and reused across many calls to
    `generate_audio()` (model load is the expensive part). Both `eval_wer.py`
    and the no-gibberish/interruption integration tests import this.
    """
    if config is None:
        config = VoxtralTrainConfig()
    dev = torch.device(device if torch.cuda.is_available() or "cpu" in str(device) else "cpu")

    model = build_model(config, dev)
    if ckpt_path:
        load_checkpoint(model, ckpt_path, dev)

    tok_cfg = config.voxtral_tokenizer_config
    tokenizer = VoxtralTokenizer(tok_cfg).to(device=dev, dtype=torch.float16)

    return InferencePipeline(model=model, tokenizer=tokenizer, config=config, device=dev)


def encode_prompt_audio(
    audio: np.ndarray | torch.Tensor,
    sample_rate: int,
    tokenizer: VoxtralTokenizer,
    language: str,
    n_tokens: Optional[int] = None,
) -> torch.Tensor:
    """Tokenize a raw waveform into a 1-D prompt tensor for `generate_audio`.

    `language` is REQUIRED (Phase 1 contract — no silent English fallback).
    If `n_tokens` is set, truncates to the first N tokens (useful for short
    "prompt with first 2 seconds" pattern in WER eval).
    """
    if isinstance(audio, np.ndarray):
        audio = torch.from_numpy(audio.astype(np.float32))
    if audio.dim() == 1:
        audio = audio.unsqueeze(0)
    if audio.dim() == 2 and audio.size(0) > 1:
        audio = audio.mean(dim=0, keepdim=True)
    audio = audio.unsqueeze(0)  # (1, 1, T)

    target_sr = 24_000
    if sample_rate != target_sr:
        audio = torchaudio.functional.resample(audio, sample_rate, target_sr)

    device = next(tokenizer.parameters()).device
    audio = audio.to(device=device, dtype=torch.float16)

    tokens, _meta = tokenizer.encode(audio, target_sr, language=language)
    tokens = tokens.squeeze(0)
    if n_tokens is not None and tokens.numel() > n_tokens:
        tokens = tokens[:n_tokens]
    return tokens


def generate_audio(
    pipeline: InferencePipeline,
    *,
    prompt: Optional[torch.Tensor] = None,
    prompt_audio: Optional[np.ndarray | torch.Tensor] = None,
    prompt_sample_rate: int = 24_000,
    prompt_tokens: int = 100,
    language: str = "eng",
    max_windows: int = 150,
    temperature: float = 0.8,
    top_k: Optional[int] = 250,
    repetition_penalty: float = 1.2,
    return_tokens: bool = False,
) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
    """Generate audio with one call. Entrypoint used by tests + eval_wer.

    Exactly one of `prompt` / `prompt_audio` may be supplied (or neither, for
    unconditional generation from a random text token). Returns a 1-D float32
    waveform on CPU at 24 kHz; with `return_tokens=True`, returns
    `(waveform, full_token_sequence)` so the interruption-emission test can
    inspect the model-stream text tokens directly.
    """
    if prompt is not None and prompt_audio is not None:
        raise ValueError("pass at most one of prompt / prompt_audio")

    if prompt_audio is not None:
        prompt = encode_prompt_audio(
            prompt_audio, prompt_sample_rate, pipeline.tokenizer,
            language=language, n_tokens=prompt_tokens,
        )

    tokens = generate_tokens(
        model=pipeline.model,
        prompt=prompt,
        max_windows=max_windows,
        temperature=temperature,
        top_k=top_k,
        device=pipeline.device,
        repetition_penalty=repetition_penalty,
    )

    waveform = tokens_to_audio(tokens, pipeline.tokenizer)
    waveform = waveform.detach().cpu().float()
    if waveform.dim() == 1:
        waveform = waveform.unsqueeze(0)

    if return_tokens:
        return waveform, tokens.detach().cpu()
    return waveform


SILENCE_TOKEN_ID = 27  # SP control token <|silence|>; see data/tokenizer/omnivoxtral_sp.vocab.


@torch.no_grad()
def generate_dual_stream(
    pipeline: InferencePipeline,
    *,
    user_audio: np.ndarray | torch.Tensor,
    user_sample_rate: int,
    language: str,
    max_windows: int = 150,
    temperature: float = 0.8,
    top_k: Optional[int] = 250,
    speech_rms_threshold: float = 0.005,
) -> dict:
    """Dual-stream generation: real user audio interleaved with autoregressive
    model output. Used by `test_model_emits_silence_during_user_speech`.

    The pipeline's model MUST be built with `dual_stream=True` (stride=42) — we
    raise otherwise. Per the dual-stream layout, each 42-token window is:
        [user_text(1), user_audio(20), model_text(1), model_audio(20)]

    Returns a dict with:
        waveform:           1-D float32 model-side audio at 24 kHz
        model_text_tokens:  (max_windows,) int — emitted model_text per window
        user_speech_mask:   (max_windows,) bool — True where user RMS > threshold
        full_tokens:        the full interleaved sequence (debug)

    The user_speech_mask is computed from the *raw* user_audio energy at each
    200ms window — an honest "is the user speaking right now?" signal, not the
    model's interpretation of it.
    """
    model = pipeline.model
    if not getattr(model.config, "dual_stream", False):
        raise ValueError(
            "generate_dual_stream requires a model built with dual_stream=True. "
            "Pass DUAL_STREAM=true via env or set VoxtralTrainConfig(dual_stream=True)."
        )

    stream_stride = model.config.stream_stride  # 21
    stride = model.config.stride                # 42 (dual-stream)
    num_q = model.config.num_codebooks          # 8
    text_vocab = model.config.text_vocab_size
    codebook_size = model.config.codebook_size
    audio_per_window = model.config.text_to_audio_factor  # 20
    device = pipeline.device

    if isinstance(user_audio, np.ndarray):
        user_audio_t = torch.from_numpy(user_audio.astype(np.float32))
    else:
        user_audio_t = user_audio.float()
    if user_audio_t.dim() == 2 and user_audio_t.size(0) > 1:
        user_audio_t = user_audio_t.mean(dim=0)
    user_audio_t = user_audio_t.flatten()

    # Energy-based user_speech_mask, one bool per 200ms window.
    target_sr = 24_000
    if user_sample_rate != target_sr:
        user_audio_t = torchaudio.functional.resample(
            user_audio_t.unsqueeze(0), user_sample_rate, target_sr
        ).squeeze(0)
    samples_per_window = target_sr // 5  # 4800 samples per 200ms
    user_mask = torch.zeros(max_windows, dtype=torch.bool)
    for w in range(max_windows):
        chunk = user_audio_t[w * samples_per_window : (w + 1) * samples_per_window]
        if chunk.numel() == 0:
            break
        rms = float(chunk.pow(2).mean().sqrt())
        user_mask[w] = rms > speech_rms_threshold

    # Pre-tokenize the user stream — we need its text + audio tokens to inject
    # at each window's user-portion. This uses the *single-stream* tokenizer
    # because we only want the per-window 21-token tuple, not the dual layout.
    user_audio_in = user_audio_t.unsqueeze(0).unsqueeze(0).to(device).to(torch.float16)
    user_tokens, _ = pipeline.tokenizer.encode(
        user_audio_in, target_sr, language=language,
    )
    user_tokens_flat = user_tokens.squeeze(0).to(device)  # 1-D, stride-21 layout

    context = torch.empty((1, 0), dtype=torch.long, device=device)
    model_text_emitted = []

    for win_idx in range(max_windows):
        # 1) Inject the user-side window (21 tokens) from the pre-tokenized buffer.
        u_start = win_idx * stream_stride
        u_end = u_start + stream_stride
        if u_end > user_tokens_flat.numel():
            # User audio exhausted — pad with silence text token + zero codes.
            user_window = torch.cat([
                torch.tensor([SILENCE_TOKEN_ID], device=device),
                torch.full((stream_stride - 1,), text_vocab, device=device, dtype=torch.long),
            ])
        else:
            user_window = user_tokens_flat[u_start:u_end]
        context = torch.cat([context, user_window.unsqueeze(0)], dim=1)

        # 2) Generate model_text (1 token).
        _hidden, logits = model._temporal_forward(context)
        text_logits = logits[:, -1, :text_vocab]
        m_text = model._sample_token(text_logits, temperature, top_k)
        context = torch.cat([context, m_text], dim=1)
        model_text_emitted.append(int(m_text.item()))

        # 3) Generate model_audio (20 tokens) via depth.
        audio_generated = 0
        while audio_generated < audio_per_window:
            hidden, _ = model._temporal_forward(context)
            h_last = hidden[:, -1, :]
            frame_tokens = model.depth.generate(h_last, temperature=temperature, top_k=top_k)
            tokens_needed = min(num_q, audio_per_window - audio_generated)
            for q in range(tokens_needed):
                global_tok = text_vocab + q * codebook_size + frame_tokens[:, q]
                context = torch.cat([context, global_tok.unsqueeze(1)], dim=1)
            audio_generated += tokens_needed

    # Decode the model-stream audio: extract the model_audio chunks across all
    # windows, build a stride-21 single-stream layout, decode via Mimi.
    full = context.squeeze(0)
    model_only = []
    for w in range(max_windows):
        offset = w * stride + stream_stride  # start of model-side within window
        model_only.append(full[offset : offset + stream_stride])
    model_only_tokens = torch.cat(model_only).unsqueeze(0)  # (1, 21*max_windows)
    waveform = tokens_to_audio(model_only_tokens, pipeline.tokenizer)

    return {
        "waveform": waveform.detach().cpu().float(),
        "model_text_tokens": torch.tensor(model_text_emitted, dtype=torch.long),
        "user_speech_mask": user_mask,
        "full_tokens": full.detach().cpu(),
    }


def main():
    parser = argparse.ArgumentParser(description="Generate audio from OmniVoxtral")
    parser.add_argument("--ckpt_path", type=str, default=None)
    parser.add_argument("--prompt_file", type=str, default=None)
    parser.add_argument("--prompt_tokens", type=int, default=100)
    parser.add_argument("--max_windows", type=int, default=20, help="Windows to generate (~4s at 5Hz, stride=21)")
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top_k", type=int, default=250, help="Top-k filtering for sampling (250=good default, None=no filter)")
    parser.add_argument("--output", type=str, default="generated.wav")
    parser.add_argument("--repetition_penalty", type=float, default=1.2, help="Repetition penalty for text tokens (1.0=off, 1.2=default)")
    parser.add_argument("--language", type=str, default="eng", help="ISO 639-3 language tag for the SP control token")
    parser.add_argument("--device", type=str, default="cuda:0")
    args = parser.parse_args()

    config = VoxtralTrainConfig()

    print("=== OmniVoxtral Generation ===")
    print(f"  Model: {config.mistral_pretrained_path}")
    print(f"  Depth: {config.depth_num_layers}L")
    print(f"  Checkpoint: {args.ckpt_path or 'random init'}")
    print(f"  Language: {args.language}")
    print(f"  Windows: {args.max_windows} (~{args.max_windows / 5:.1f}s audio at 5Hz)")
    print(f"  Temperature: {args.temperature}")
    print()

    pipeline = load_inference_pipeline(args.ckpt_path, config=config, device=args.device)

    prompt = None
    if args.prompt_file:
        prompt_data = np.load(args.prompt_file)
        prompt = torch.from_numpy(prompt_data).squeeze()
        if args.prompt_tokens and args.prompt_tokens < len(prompt):
            prompt = prompt[:args.prompt_tokens]
        print(f"Prompt: {len(prompt)} tokens from {args.prompt_file}")

    waveform = generate_audio(
        pipeline,
        prompt=prompt,
        language=args.language,
        max_windows=args.max_windows,
        temperature=args.temperature,
        top_k=args.top_k,
        repetition_penalty=args.repetition_penalty,
    )
    print(f"  Audio shape: {waveform.shape}")
    print(f"  Duration: {waveform.shape[-1] / 24000:.2f}s at 24kHz")

    torchaudio.save(args.output, waveform, 24000)
    print(f"\nSaved: {args.output}")
    print("=== Done ===")


if __name__ == "__main__":
    main()
